# Debian 12
dist="bookworm"

# profile sẽ đưa vào ISO và tự chọn khi cài
profiles="webstack"
auto_profiles="webstack"

# chỉ lấy main (nginx + php đều nằm trong main)
mirror_components="main"

# Mirror dùng lúc BUILD (cài đặt thì ta tắt network mirror bằng preseed)
debian_mirror="http://deb.debian.org/debian/"

# (Tuỳ chọn) Nếu bạn muốn ISO không chứa security/updates để nhẹ hơn,
# có thể bỏ comment 2 dòng dưới (build sẽ không kéo repo đó).
#security_mirror=""
#updates_mirror=""
local_packages="extras/local-package/*.deb"

BOOT_TIMEOUT=50
